#pragma once
namespace glyph {
inline constexpr const char* view_head=R"GLYPH(<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Glyph · Graph Explorer</title>
<style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#101419;color:#dde5ed}*{box-sizing:border-box}body{margin:0}header{padding:22px 28px;border-bottom:1px solid #2a343f;display:flex;gap:20px;align-items:center}h1{font-size:22px;margin:0;letter-spacing:-.6px}header small{color:#89a0b5}#source{margin-left:auto;font:12px monospace;max-width:45%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}nav{display:flex;align-items:center;flex-wrap:wrap;gap:14px;padding:15px 28px;border-bottom:1px solid #2a343f}select,input,button{font:inherit;color:inherit;background:#1c252f;border:1px solid #3b4b5e;border-radius:7px;padding:8px 10px}input[type=checkbox]{accent-color:#62d8bc}button{cursor:pointer}button:hover{background:#2c3d4a}label{font-size:13px}main{display:grid;grid-template-columns:minmax(400px,1fr) 350px;height:calc(100vh - 145px)}#canvas{overflow:auto;background-image:radial-gradient(#28333e 1px,transparent 1px);background-size:22px 22px}svg{display:block;margin:auto}aside{overflow:auto;padding:25px;border-left:1px solid #2a343f;background:#141b23}h2{font-size:21px;margin:8px 0}h3{font-size:11px;text-transform:uppercase;letter-spacing:1.4px;color:#8ea4b9;margin:25px 0 9px}p,pre{font-size:13px;line-height:1.7}pre{white-space:pre-wrap;overflow-wrap:anywhere;color:#b6d4df}#stats{font-size:12px;color:#8ea4b9}.badge{display:inline-block;padding:4px 9px;background:#23382f;color:#83dcbc;border-radius:5px;font-size:11px}.node{cursor:pointer;outline:none}.node rect{fill:#1b2631;stroke:#42576c;stroke-width:1.3}.node:hover rect,.node:focus rect,.node.selected rect{stroke:#76e4c3;stroke-width:2.5}.node.pending rect{stroke:#f1b75e;stroke-dasharray:5 3}.node.dim{opacity:.23}.node text{fill:#e0e9f2;font-family:system-ui,sans-serif}.node .sub{fill:#91aabe;font:12px monospace}.node .status{fill:#e8b96b;font-size:11px}.edge{fill:none;stroke:#61bda7;stroke-width:1.6;opacity:.75}.edge.control{stroke:#687d91;stroke-dasharray:4 6;opacity:.5}.edge-label{fill:#9ddacb;font:10px monospace;paint-order:stroke;stroke:#101419;stroke-width:4px;stroke-linejoin:round}.terminal rect{fill:#142e2a;stroke:#37675e}.legend{color:#8fa6bc;font-size:12px}#empty{padding:20px;display:none}@media(max-width:850px){main{grid-template-columns:1fr;height:auto}#canvas{height:65vh}aside{border-left:0;border-top:1px solid #2a343f}#source{display:none}}
</style></head><body>
<header><h1>◈ Glyph</h1><small>GRAPH EXPLORER</small><span id="source"></span></header>
<nav><select id="flow" aria-label="Flow"></select><input id="search" type="search" placeholder="Node 또는 binding 검색" aria-label="Node 검색"><label><input id="data" type="checkbox" checked> Data</label><label><input id="control" type="checkbox" checked> Control</label><button id="minus" aria-label="축소">−</button><button id="plus" aria-label="확대">+</button><button id="reset">100%</button><span id="stats"></span></nav>
<main><section id="canvas" aria-label="Flow graph"><svg id="graph" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="컴파일된 Flow 연결"></svg></section><aside id="details" aria-live="polite"></aside></main>
<script id="glyph-data" type="application/json">)GLYPH";
inline constexpr const char* view_tail=R"GLYPH(</script>
<script>
'use strict';
const program=JSON.parse(document.getElementById('glyph-data').textContent);
const $=id=>document.getElementById(id), svg=$('graph'), ns='http://www.w3.org/2000/svg';
let current=program.flows[0], zoom=1, selected=null;
$('source').textContent=program.source;
for(const f of program.flows){const o=document.createElement('option');o.value=f.name;o.textContent=f.name;$('flow').append(o)}
function el(tag,attrs={},text){const e=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,v);if(text!==undefined)e.textContent=text;return e}
function detail(title,subtitle,sections){const box=$('details');box.replaceChildren();const b=document.createElement('span');b.className='badge';b.textContent=subtitle;box.append(b);const h=document.createElement('h2');h.textContent=title;box.append(h);for(const [name,value] of sections){const label=document.createElement('h3');label.textContent=name;const body=document.createElement('pre');body.textContent=value||'—';box.append(label,body)}}
function overview(){detail(current.name,current.atomic?'ATOMIC FLOW':'FLOW',[
['입력',current.inputs.map(p=>p.name+': '+p.type).join('\n')],['출력',current.output],['효과',current.effects.join('\n')||'none'],['전파되는 Failure',current.failures.join('\n')],['읽는 방법','실선: 실제 데이터 의존성\n점선: 실행 순서\n주황 테두리: 구현이 필요한 Node\n\nNode를 선택하면 계약과 구현을 봅니다.\n상수 인수에는 데이터 Edge가 없습니다.']])}
function inspect(item){selected=item.id;draw();if(!item.step){overview();return}const st=item.step,n=program.nodes[st.node];const sections=[['Binding',st.binding+' · 호출 line '+st.line],['입력',n.inputs.map(p=>p.name+': '+p.type).join('\n')],['출력',n.output]];for(const key of ['require','ensure','effect','read','write','fail','intent','impl'])if(n.sections[key])sections.push([key,n.sections[key].join('\n')]);detail(n.name,program.unresolved.includes(n.name)?'UNRESOLVED':'RESOLVED · LINE '+n.line,sections)}
function draw(){svg.replaceChildren();const width=720,height=(current.steps.length+2)*140+60;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('width',width*zoom);svg.setAttribute('height',height*zoom);
const defs=el('defs');for(const [id,color] of [['arrow','#61bda7'],['control-arrow','#687d91']]){const m=el('marker',{id,viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:6,markerHeight:6,orient:'auto'});m.append(el('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:color}));defs.append(m)}svg.append(defs);
const items=[{id:'input',title:'Flow input',sub:current.inputs.map(p=>p.name+': '+p.type).join(' · ')||'Unit'},...current.steps.map(s=>({id:s.id,title:s.node,sub:s.binding+' → '+program.nodes[s.node].output,step:s})),{id:'output',title:'Flow output',sub:current.output}];
const pos=new Map(items.map((n,i)=>[n.id,{x:290,y:30+i*140}]));let lane=0;
for(const edge of current.edges){if(!$(edge.kind).checked)continue;const a=pos.get(edge.from),b=pos.get(edge.to);let d;if(edge.kind==='control')d=`M ${a.x+170} ${a.y+90} L ${b.x+170} ${b.y}`;else{const x=65+(lane++%8)*23;d=`M ${a.x} ${a.y+45} C ${x} ${a.y+45}, ${x} ${b.y+45}, ${b.x} ${b.y+45}`;}const path=el('path',{d,class:'edge '+edge.kind,'marker-end':`url(#${edge.kind==='data'?'arrow':'control-arrow'})`});path.append(el('title',{},edge.label||'Execution order'));svg.append(path);if(edge.kind==='data'){const label=el('text',{x:20+((lane-1)%3)*13,y:(a.y+b.y)/2+45,class:'edge-label'},edge.label);label.append(el('title',{},edge.label));svg.append(label)}}
const query=$('search').value.toLowerCase();let matches=0;
for(const item of items){const p=pos.get(item.id),pending=item.step&&program.unresolved.includes(item.title),match=!query||[item.title,item.sub].join(' ').toLowerCase().includes(query);if(item.step&&match)matches++;const group=el('g',{class:'node'+(!item.step?' terminal':'')+(pending?' pending':'')+(selected===item.id?' selected':'')+(!match?' dim':''),tabindex:0,role:'button','aria-label':item.title+' '+item.sub,transform:`translate(${p.x},${p.y})`});group.append(el('rect',{width:340,height:90,rx:12}));group.append(el('text',{x:18,y:29,'font-size':16},item.title));const sub=el('text',{x:18,y:53,class:'sub'},item.sub.length>39?item.sub.slice(0,36)+'…':item.sub);sub.append(el('title',{},item.sub));group.append(sub);const effects=item.step?(program.nodes[item.title].sections.effect||[]).filter(x=>x!=='none'):[];group.append(el('text',{x:18,y:75,class:'status'},pending?'● implementation needed':effects.join(' · ')));group.addEventListener('click',()=>inspect(item));group.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inspect(item)}});svg.append(group)}
$('stats').textContent=`${current.steps.length} nodes · ${current.edges.filter(e=>e.kind==='data').length} data edges`+(query?` · ${matches} matches`:'');$('reset').textContent=Math.round(zoom*100)+'%';}
$('flow').onchange=()=>{current=program.flows.find(f=>f.name===$('flow').value);selected=null;$('canvas').scrollTop=0;overview();draw()};for(const id of ['search','data','control'])$(id).addEventListener('input',draw);$('plus').onclick=()=>{zoom=Math.min(2,zoom+.15);draw()};$('minus').onclick=()=>{zoom=Math.max(.4,zoom-.15);draw()};$('reset').onclick=()=>{zoom=1;draw()};overview();draw();
</script></body></html>)GLYPH";
}
